### ISSUE TITLE
ec2_scaling_policy: NameError: global name 'AWS_REGIONS' is not defined

### ISSUE THREAD

**Issue by berenddeboer** [ansible/ansible-modules-core#1193]
When using ec2_scaling_policy I get this error: NameError: global name 'AWS_REGIONS' is not defined (region = dict(aliases=['aws_region', 'ec2_region'], choices=AWS_REGIONS),)

AWS_REGIONS is defined in two other modules, but not in others. Probably should be shared? Or copied across?

**Comment by bcoca** [comment]
actually that line is redundant as it already get's region from the common ec2.py settings

**Comment by bcoca** [comment]
test the PR above, it should solve the issue

**Comment by jonhadfield** [comment]
https://github.com/ansible/ansible-modules-core/pull/1195 fixed the same issue for me.
Also, same issue (NameError: global name 'AWS_REGIONS' is not defined) in ec2_metric_alarm resolved by removing line 263:
`region=dict(aliases=['aws_region', 'ec2_region'], choices=AWS_REGIONS),`
Assume it would be easier for you to amend your PR than for me to submit a new one?

**Comment by bcoca** [comment]
also fixed ec2_metric_alarm

**Comment by kclausen-tm** [comment]
Seems like the issue is still there. I'm getting the same error from ec2_metric_alarm with a fresh pull.
