### ISSUE TITLE
ec2_lc fails with TypeError: LaunchConfiguration:test-lc is not JSON serializable (devel branch)

### ISSUE THREAD

**Issue by joshm** [ansible/ansible-modules-core#1655]
Running a lc create as simple as:

```
- name: s launch configuration
  ec2_lc:
    name: test-lc
    instance_type: m3.medium
    region: us-west-2
    state: present
```

Returns:

`TASK [s_setup : s_setup : s launch configuration] *******************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: LaunchConfiguration:test-lc is not JSON serializable
fatal: [localhost]: FAILED! => {"invocation": {"module_name": "ec2_lc", "module_args": {"instance_type": "m3.medium", "region": "us-west-2", "name": "test-lc", "state": "present"}}, "failed": true, "changed": false, "parsed": false}`

**Comment by joshm** [comment]
I believe it is this: https://github.com/ansible/ansible-modules-core/commit/5e674ddcfc3ab317d2aa05fc84dfe206768cfdab#diff-74356b4e26d3b0a785194e2aad7fe7f4

Removing that, fixes the issue

**Comment by evanccnyc** [comment]
Yup just ran into this bug as welll..probably should back this out since it breaks Launch Config.

**Comment by bcoca** [comment]
reverted the commit, closing this issue

**Comment by evanccnyc** [comment]
Hmmm i just pulled down ansible and reran with this patch backed out and still seeing it...I am going to dig a bit deeper.

**Comment by bcoca** [comment]
run with -vvvv so we get the full traceback

**Comment by evanccnyc** [comment]
That pull request I just posted should fix this problem.

**Comment by evanccnyc** [comment]
Traceback is posted in the pull request. If you want to double check.

**Comment by vuorse** [comment]
The latest version of ec2_lc is indeed broken. Haven't isolated the actual issue yet, but by backing out to a version b91a232 it works so definately something committed since then has caused the issue.

**Comment by abadger** [comment]
@robbwagoner So in https://github.com/ansible/ansible-modules-core/pull/497 we added a LaunchConfig  object into the return value for ec2_lc.  Unfortunately, that object can only be turned into json some of the time.  Can you tell us what fields of LaunchConfig we care about?  Or which ones might not be python basic types?  One of the other return values is also apparently a non-basic type sometimes... we'll have to track that one down to.

**Comment by abadger** [comment]
@vuorse Since the revert didn't fix things, the commit was added back in.  I think the value that the commit adds to the return is definitely one way to trigger this but there may be another value being returned that is also a problem.

**Comment by abadger** [comment]
@evanccnyc and I came up with this fix on IRC: https://github.com/ansible/ansible-modules-core/commit/8a9405a55bc5ac814b6e952acd2df0a6467e8a27  That should retain the results values while fixing this bug.  Feel free to ping me on IRC or open a new bug if things still aren't 100% correct.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by evanccnyc** [comment]
This is back again with the following error:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/Users/xxx/.ansible/tmp/ansible-tmp-1438873502.61-100274916250421/ec2_lc", line 2210, in <module>
    main()
  File "/Users/xxx/.ansible/tmp/ansible-tmp-1438873502.61-100274916250421/ec2_lc", line 2206, in main
    create_launch_config(connection, module)
  File "/Users/xxx/.ansible/tmp/ansible-tmp-1438873502.61-100274916250421/ec2_lc", line 2153, in create_launch_config
    result=result)
  File "/Users/xxx/.ansible/tmp/ansible-tmp-1438873502.61-100274916250421/ec2_lc", line 1476, in exit_json
    print self.jsonify(kwargs)
  File "/Users/xxx/.ansible/tmp/ansible-tmp-1438873502.61-100274916250421/ec2_lc", line 1454, in jsonify
    return json.dumps(new_data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: InstanceMonitoring(true) is not JSON serializable

fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "parsed": false}
``
```

**Comment by fvant** [comment]
I run into the same issue, diving in and running a bare minumum boto example shows the same symptoms: I get a list of names, not the LC details

> > > import boto.ec2.autoscale
> > > con=boto.ec2.autoscale.connect_to_region('eu-west-1')
> > > con.get_all_launch_configurations()
> > > [LaunchConfiguration:removed, LaunchConfiguration:removed2, LaunchConfiguration:removed3]

**Comment by abadger** [comment]
Are you running from a git checkout or from the 1.9.3 release candidate?
The rod reported have been fixed in those places but naturally, those fixes
can't retroactively go into 1.9.2 since it's already released.

Since this bug is closed, if you find this is still a problem with one of
those, could you open a new ticket?  That will help ensure any remaining
problems are not overlooked.

**Comment by fvant** [comment]
I run from git checkout,  but as only using boto without Ansible also gives the wrong result, therefore I think the problem lies with boto/aws  not Ansible.

**Comment by fvant** [comment]
Got it working after running a sudo python setup.py install, looked like not all the latest Ansible code was 'live'.
