### ISSUE TITLE
Assemble module does not find source directory

### ISSUE THREAD

**Issue by paulbeattie** [ansible/ansible-modules-core#1949]
# Issue Type:

Bug report for 'assemble' module
# Ansible Version:

1.9.2
# Environment:

Mac OS 10.10.4 / Ansible from Homebrew
# Summary:

Passing src directory raises an error that it does not exist, running ls on the path it returns yields the correct path which is present.
# Steps to Reproduce:
1. Create src directory
2. Use this src directory as source for assemble task.
3. Run playbook and notice failure "msg: Source (/Users/paulbeattie/ansible/ansible-rails/roles/common/files/pub_keys) does not exist"

I've put together a test here: https://github.com/paulbeattie/ansible-assemble-bug
# Expected Results:

Directory is discovered and used to assemble file from
# Actual Results:

The failure message is displayed, it also contains very little information about the problem, it should be obvious what the problem is/next steps.
# Notes

I tried rolling back to Ansible 1.8 but this still seems to be an issue on there. This has also been tested on another machine and the issue is still present.

**Comment by bcoca** [comment]
can you test in latest devel? this should be working there.

also you should not need playbook_dir anymore.

**Comment by paulbeattie** [comment]
@bcoca I've tested it in the latest devel just now and it has exactly the same result.

**Comment by bcoca** [comment]
I tested your example and it works fine, also the error message you show does not seem to be related to the example.

**Comment by bcoca** [comment]
I just changed the dest to =/tmp/loads_o_files as I dont have a vagrant user.

```
PLAY [Ansible Assemble test] ***************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [assemble dest=/tmp/lots_of_concat src={{ playbook_dir }}/loads_o_files] **
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   
```

**Comment by paulbeattie** [comment]
I've put together a proper test playbook which I've added to the same repo (https://github.com/paulbeattie/ansible-assemble-bug). Again using devel this is still a problem. I'm not entirely sure why. Running the playbook and testing where it's running the conditions for it existing and being a directory it fails. Running this on the Python REPL yields the opposite result.

This is the output when I run it using the test playbook from OS X 10.10.4 to a Digital Ocean Ubuntu 14.04x64 base: <img width="1360" alt="screenshot 2015-08-21 22 50 07" src="https://cloud.githubusercontent.com/assets/106584/9419857/5e6f340e-4857-11e5-9ca0-a94ad0a7e2f0.png">

**Comment by bcoca** [comment]
I just ran, no errors:

```
PLAY ***************************************************************************

TASK [common : Add authorized deploy keys to deploy user] **********************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0   
```

**Comment by bcoca** [comment]
I think i know what is going on, I'm running locally so the directories line up, but you are executing remotely and have not added `remote_src=no` as assemble by default assumes the source dir is on the target host.

**Comment by bcoca** [comment]
```
---
  - name: Add authorized deploy keys to deploy user
    assemble:
      src: "{{ playbook_dir}}/roles/common/files/pub_keys"
      dest: /tmp/lots_of_concat
      backup: yes
      remote_src: False
```

**Comment by paulbeattie** [comment]
:tada: that's it! Thanks for being so responsive on this one! I really appreciate it.

I'll put a PR in over the weekend to flesh out the examples a bit more for assemble, including this use case.
