### ISSUE TITLE
a2enmod/a2dismod multiline output

### ISSUE THREAD

**Issue by n0trax** [ansible/ansible-modules-core#2081]
**Issue Type:** Bugfix Pull Request

**Ansible Version:** ansible 1.9.2

**Summary:**

In some cases a2enmod/a2dismod response message has multiple lines. E.g:

"Your MPM seems to be threaded. Selecting cgid instead of cgi.
Module cgid already enabled"

Because of that an item like
`- apache2_module name=cgi state=absent`
is always changed.

**Solution:** Additional multiline Option in the regular expression match.

```
--- apache2_module-orig.py      2015-09-15 12:34:03.448258630 +0200
+++ apache2_module.py   2015-09-15 12:34:40.888259142 +0200
@@ -56,7 +56,7 @@

     result, stdout, stderr = module.run_command("%s %s" % (a2dismod_binary, name))

-    if re.match(r'.*\b' + name + r' already disabled', stdout, re.S):
+    if re.match(r'.*\b' + name + r' already disabled', stdout, re.S|re.M):
         module.exit_json(changed = False, result = "Success")
     elif result != 0:
         module.fail_json(msg="Failed to disable module %s: %s" % (name, stdout))
@@ -71,7 +71,7 @@

     result, stdout, stderr = module.run_command("%s %s" % (a2enmod_binary, name))

-    if re.match(r'.*\b' + name + r' already enabled', stdout, re.S):
+    if re.match(r'.*\b' + name + r' already enabled', stdout, re.S|re.M):
         module.exit_json(changed = False, result = "Success")
     elif result != 0:
         module.fail_json(msg="Failed to enable module %s: %s" % (name, stdout))
```

**Comment by evanccnyc** [comment]
Better to submit this as a pull request.

**Comment by robinro** [comment]
@bcoca 
This change does NOT fix the issue!

The multiline option does not help, because `name = cgi` and there is text between "cgi" and "already enabled". Don't confure `cgi` with `cgid`.

The regex does not even contain any whitespace, so the multiline option has no effect at all. Please revert the patch as it makes to code more complicated without fixing anything.

**Comment by robinro** [comment]
@bcoca 
see #2082 for the discussion on this issue as well.

You can merge pull-request #2091, which is a patch of mine that fixes a problem with openSuSE on exactly the same two lines. I updated it to revert the changes done for this issue.

A real fix for the original issue of this thread would be a more complex regexp. On the other hand one could argue that the corresponding playbook should be fixed as one could provide the correct module (`cgid` instead of `cgi`). As stated in #2082 I would suggest to just close this issue.

**Comment by n0trax** [comment]
@robinro is definitely right. My Patch does not fix the issue.

An other idea is to parse the output of `apachectl -M` to figure out if a module is enabled or not.
The output is identical on RedHat, SuSE and Debian based systems. Unfortunatly the command can differ along OS-Versions. On RedHat systems apachectl is not used and I'm not sure if all SuSE Versions are using it.

PS: As Robin mentioned, I fixed the cgi/cgid problem in my playbook. But a hint would have
been very nice. Maybe it is a good idea to check if apache is running threaded and print a info message if any actions on cgi module are requested. AFAIK the cgi module is the only one, which is replaced by a2enmod/a2dismod on its own.
