### ISSUE TITLE
digital_ocean module: Add support for v2 API

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible-modules-core#209]
##### Issue Type:

Feature idea
##### Ansible Version:

Next
##### Environment:

N/A
##### Summary:

The digital ocean API was recently updated to v2 and includes a set of new features that make working with Digital Ocean much simpler, including referring to images and regions by string names rather than IDs, and the addition of droplet metadata through the `user_data` parameter.
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by geerlingguy** [comment]
See original post over in ansible/ansible#8563.

**Comment by geerlingguy** [comment]
This would be nice for a variety of reasons, but one of the best improvements would be the addition of the `user_data` property, allowing for tagging and adding extra data to droplets, so they're not all lumped together in one huge 'digital ocean hosts' bucket when using dynamic inventories.

**Comment by geerlingguy** [comment]
Updated, thanks Ansibot :)

**Comment by geerlingguy** [comment]
Also of note: the dopy library supports v2 as of 24 days ago: https://github.com/devo-ps/dopy/commit/407a6fe3c2b98a0ea192c003c7d49b79b17a05a3

**Comment by resmo** [comment]
:+1:

**Comment by hilem** [comment]
:+1:

**Comment by hilem** [comment]
Not having the user_data attribute on droplet creation that's available in the API v2 is currently blocking me from being able to create coreos droplets on digital ocean through Ansible.  Does anyone know of a workaround besides, not using Ansible, for this specific scenario?

**Comment by xavimb** [comment]
You should be able to create CoreOS droplets anyway with Ansible. Check the documentation at http://docs.ansible.com/digital_ocean_module.html and https://developers.digitalocean.com/v1/. You'll need to fetch some IDs from the old api to know the size of the droplet and the image ID.

**Comment by hilem** [comment]
Going that route, requires being able to edit the cloud-config after creation which I haven't seen any documentation on how you would go about doing that.  The only reference I've found implies that it can't be done, it has to be set on creation.  Just creating a coreos droplet is pretty pointless without being able to set that.  The whole coreos philosophy seems to be geared towards -- its easier to teardown and setup again than to do maintenance.  I don't see anything in either of those documentation links that would help.  If I'm missing something please let me know.

**Comment by gawbul** [comment]
:+1: would be great to have v2 API support. Anyone working on this?

**Comment by gawbul** [comment]
@geerlingguy Good about dopy. This is the current dependency for the digital_ocean module is it not? This would mean not relying on skiff, which appears to be a v2 only API, making it more appropriate for maintaining backward compatibility.

**Comment by valberg** [comment]
I have started work on this and have a PR at https://github.com/ansible/ansible-modules-core/pull/580 - testing and help is highly appreciated :)

**Comment by linefeedse** [comment]
Is there a reason for keeping the V1 API around? Otherwise I have a complete switchover to V2 ready here https://github.com/ansible/ansible-modules-core/pull/998

**Comment by geerlingguy** [comment]
Also, FYI, The v2 API is [finally out of beta](https://www.digitalocean.com/company/blog/apiv2-officially-leaves-beta/) :).

**Comment by skottler** [comment]
I've merged @linefeedse's pull request in #998. Thanks folks!

**Comment by SilverSols** [comment]
@skottler : Good work. I've just been trying this : 

```
myserver $ ansible --version
ansible 2.0.0 (devel 4205d74b11) last updated 2015/04/28 01:45:38 (GMT +100)
```

Although the code/docs have updated the key:value pair key names, the code only accepts the old key names.  It does however accept the slugs as intended. 

My example file works using the 2.0 code as follows : 

```
---
- hosts: localhost
  connection: local
  tasks:
  - name: Add a droplet to Digital Ocean
    digital_ocean: >
      api_token=**yourtoken**
      state=present
      command=droplet
      name=mydroplet
      ssh_key_ids=123456
      size_id=512mb
      region_id**=lon1
      image_id=ubuntu-14-04-x64
      unique_name=yes
    register: mydroplet
```

This fires up a droplet. Note the size_id, region_id and image_id are still present. Using size_slug, region_slug or image_slug raises an error : 

```
TASK: [Add a droplet to Digital Ocean] ****************************************
failed: [localhost] => {"failed": true}
msg: unsupported parameter for module: image_slug
```

Not sure how to raise this as an issue - commenting here.

**Comment by SilverSols** [comment]
@skottler

**Comment by jloh** [comment]
I'm running into this problem now as well, same error.

**Comment by linefeedse** [comment]
Which documentation indicates that the key names have changed to "__slug"?
Dopy still used the "__id" key name and the API itself uses just "image" and "region" without any "_suffix", so slapping on a "_slug" would just introduce a third key name...
