### ISSUE TITLE
apt: Cannot downgrade a deb= package

### ISSUE THREAD

**Issue by markabey** [ansible/ansible-modules-core#327]
Issue Type: Bug report
Ansible Version: 1.6 (but module doesn't appear to have changed on latest) ubuntu 12.04
Summary:
If running the following code to downgrade a package, it fails with the error below:

Steps To Reproduce:
Install a newer version of package.deb, then use ansible to install an older one directly from the deb file.

```
- apt: deb=/path/to/old package.deb state=installed force=yes dpkg_options=force-confdef,force-confold,force-downgrade
```

Expected Results:
It installs the debian package, as force-downgrade is specified

Actual Results:

```
failed: [host] -> {"failed": true, "item": ""}
msg: A later version is already installed
```

I think the check for if the package is a newer version happens before the force-downgrade is passed onto dpkg. In apt.debfile.DebPackage(deb_file).check() it looks to check if the version is older, and returns false if it is. I can't see an option to override this in ansible

**Comment by simono** [comment]
I guess this was fixed in #333

**Comment by Rizzly** [comment]
#### Ansible Version:

1.8.2 (and devel as well, although I have not tried it there)

#### Environment:

Ubuntu 14.04.1 with dpkg 1.17.5

#### Summary:

https://github.com/ansible/ansible-modules-core/pull/333 partly fixes this by ignoring pkg.check() output, but on lines 385 and 386 in devel this is still present:

```
if force:
    options += " --force-yes"
```

I have not found any instance of dpkg that allows, or dpkg manual that documents --force-yes. I suspect that simply removing the above lines should solve the issue without side-effects (it did when I tried).

#### Steps To Reproduce:

Same as above

#### Expected Results:

Same as above

#### Actual Results:

```
failed: [host] => {"failed": true}
stderr: dpkg: error: unknown force/refuse option `yes'

Type dpkg --help for help about installing and deinstalling packages [*];
Use 'apt' or 'aptitude' for user-friendly package management;
Type dpkg -Dhelp for a list of dpkg debug flag values;
Type dpkg --force-help for a list of forcing options;
Type dpkg-deb --help for help about manipulating *.deb files;

Options marked [*] produce a lot of output - pipe it through 'less' or 'more' !

msg: dpkg --force-confdef --force-confold --force-downgrade --force-yes -i /path/to/old package.deb failed

FATAL: all hosts have already failed -- aborting
```

**Comment by tetherit** [comment]
Any workaround for this? - experiencing the same error, unknown force/refuse option and "msg: A later version is already installed" when removing force=yes :(

**Comment by Rizzly** [comment]
The problem I described is fixed by this PR https://github.com/ansible/ansible-modules-core/pull/53. That should proabably go for @markabey and @hackeron as well. Have a try!

**Comment by gregdek** [comment]
Closing per submitter request. Thanks @Rizzly!

**Comment by tetherit** [comment]
Seems to work now, thank you!
