### ISSUE TITLE
Ansible not pulling images from private Docker repository

### ISSUE THREAD

**Issue by abadger** [ansible/ansible-modules-core#940]
Report from @soupdiver Here: https://github.com/ansible/ansible/issues/10209

I've problems with Ansible automatically pulling docker images from my private repository.
I do login first via:

``` yaml
- name: login to registry
  shell: "docker login -e {{ registry_mail }} -p {{ registry_pass }} -u {{ registry_user }} {{ registry_host }}"
```

and then I tried the following instructions:

``` yaml
- name: start foo container
  docker:
    image: registry.foo:8888/app
    name: foo-app
    env: "DB_NAME=foo,APP_HOST=foo.foo,NODE_ENV=docker"
    ports: 127.0.0.1:1337:1337
    state: running

- name: start foo container
  docker:
    image: app
    registry: registry.foo:8888
    name: foo-app
    env: "DB_NAME=foo,APP_HOST=foo.foo,NODE_ENV=docker"
    ports: 127.0.0.1:1337:1337
    state: running

- name: start foo container
  docker:
    image: app
    registry: registry.foo:8888
    username: "{{ registry_user }}"
    password: "{{ registry_pass }}"
    name: foo-app
    env: "DB_NAME=foo,APP_HOST=foo.foo,NODE_ENV=docker"
    ports: 127.0.0.1:1337:1337
    state: running
```

everyone gave me an error: `msg: Docker API error: No such image`

Doing manually `docker run registry.foo:8888/app` did pull and start the image.

I had to manually insert

``` yaml
- name: pull foo container manually
  shell: docker pull registry.foo.com:8888/app
```

Any ideas?

**Comment by abadger** [comment]
Are you able to try again with a checkout from the devel branch?  There's been some large code changes in the docker module in the past few weeks.  I don't think it fixes your issue but I do think the exact error message we get now will help to narrow down where this is going wrong.

**Comment by abadger** [comment]
Mm... also, I see a report from someone else where they have a private registry working with a playbook like this:

```
  - name: main.yml | start our container
    docker:
      image: app
      name: my app
      registry: 'https://our.registry.com'
      username: "{{ docker_username }}"
      email: "{{ docker_email }}"
      password: "{{ docker_password }}"
      publish_all_ports: yes
      docker_api_version: "{{ client_api_version.stdout }}"
      state: running
```

perhaps the registry needs to have "https://" at the start?  Or perhaps the credentials for logging in need to be part of each task?

**Comment by soupdiver** [comment]
I will check that again soon and provide feedback here

**Comment by soupdiver** [comment]
I tried again with the current devel branch

``` bash
felix:ansible felix$ ansible --version
ansible 1.9 (devel 22304afd1d) last updated 2015/03/15 13:47:14 (GMT +1300)
  lib/ansible/modules/core: (detached HEAD b530afc24e) last updated 2015/03/15 14:01:42 (GMT +1300)
  lib/ansible/modules/extras: (detached HEAD 696bc60caa) last updated 2015/03/15 14:01:44 (GMT +1300)
  v2/ansible/modules/core: (detached HEAD b530afc24e) last updated 2015/03/15 14:01:46 (GMT +1300)
  v2/ansible/modules/extras: (detached HEAD 696bc60caa) last updated 2015/03/15 14:01:48 (GMT +1300)
  configured module search path = None
```

My test playbook is the following:

``` yaml
---
- hosts: ansible_test
  tasks:
    - name: start an image which is NOT present on the host yet but on the private regisrty
      docker:
        name: docker_pull_test
        registry: "registry.foo.com"
        username: "{{ registry_user }}"
        password: "{{ registry_pass }}"
        email: "{{ registry_mail }}"
        image: registry.foo.com/ubuntu:latest
        command: /bin/echo success
        state: present

    - name: remove container
      docker: 
        name: docker_pull_test
        image: registry.foo.com/ubuntu:latest
        state: absent
```

This results in:

```
failed: [coconut] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/ansible/.ansible/tmp/ansible-tmp-1426382873.48-237592096135916/docker", line 3101, in <module>
    main()
  File "/home/ansible/.ansible/tmp/ansible-tmp-1426382873.48-237592096135916/docker", line 1446, in main
    manager = DockerManager(module)
  File "/home/ansible/.ansible/tmp/ansible-tmp-1426382873.48-237592096135916/docker", line 623, in __init__
    tls=tls_config)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 51, in __init__
    'If using TLS, the base_url argument must begin with '
docker.errors.TLSParameterError: If using TLS, the base_url argument must begin with "https://".. TLS configurations should map the Docker CLI client configurations. See http://docs.docker.com/examples/https/ for API details.
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
debug1: Reading configuration data /Users/felix/.ssh/config
debug1: /Users/felix/.ssh/config line 49: Applying options for x.x.x.x
debug1: Reading configuration data /etc/ssh_config
debug1: /etc/ssh_config line 20: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to x.x.x.x closed.
```

I also tried adding **https://** to the registry url but I get the same error.

When logging in manually to the server and executing `docker login https://registry.foo.com` I get `Login Succeeded`

Also executing `docker pull registry.foo.com/ubuntu:latest` will output:

```
Pulling repository registry.foom/ubuntu
04c5d3b7b065: Download complete
511136ea3c5a: Download complete
c7b7c6419568: Download complete
70c8faa62a44: Download complete
d735006ad9c1: Download complete
Status: Downloaded newer image for registry.foom/ubuntu:latest
```

I hope this helps

**Comment by abadger** [comment]
This looks like an error about ssl to the docker server, not to the registry.  I think that's a bug in the new docker tls code.  Let me whip up a pull request for that might address that.

**Comment by abadger** [comment]
Can you try this and see if it makes this work or at least advances us to a new error? https://github.com/ansible/ansible-modules-core/pull/947

**Comment by soupdiver** [comment]
This leads me to:

```
failed: [coconut] => {"failed": true, "status": ""}
msg: Unrecognized status from pull.
```

**Comment by sharpner** [comment]
+1

**Comment by abadger** [comment]
Okay, I've pushed #937 to the repo, a fix for another error in the same code, and something to make your error more verbose.  Could you try again with what's in the devel branch and post the error message?  I think docker-py is returning a value that we're not expecting but i'll need to see the new error message to see what the value is.

**Comment by abadger** [comment]
How are you all setting up your registries with auth? The If I'm reading things correctly docker-registry package that I have installed doesn't appear to have builtin auth.  Have to setup a separate webserver to proxy to it which does basic auth.  Reading the docker-py code I'm not sure that it handles that case... stackoverflow and other googlable resources aren't very helpful in this regard either... I'm beginning to think that docker-py's username and password only work with dockerhub, not with anything you can do with your own registries.

**Comment by abadger** [comment]
Well, I've added some integration tests to check for problems using private docker registries: https://github.com/ansible/ansible/blob/devel/test/integration/roles/test_docker/tasks/registry-tests.yml

It was a bit tricky to figure out the values that should be used but everything appears to be working once I did.  From what I can see, the last playbook fragment you posted matches up with what I have in the test case.  That likely means that the way you have your httpd proxy that's doing auth setup is different than what I have and there's something that the docker module isn't anticipating in the return value from that.  You could take a look at the way nginx is setup in the registry-tests.yml file for differences.  Or post the output from the updated docker module so I can see the message that's being returned.  Otherwise I don't have any more information to show me where anything needs to be adjusted.

**Comment by soupdiver** [comment]
I tested again with the latest source

```
felix:ansible-src felix$ ansible --version
ansible 1.9 (devel d628f3f591) last updated 2015/03/28 11:19:05 (GMT +1300)
  lib/ansible/modules/core: (detached HEAD 5d776936cc) last updated 2015/03/28 11:19:20 (GMT +1300)
  lib/ansible/modules/extras: (detached HEAD 400166a655) last updated 2015/03/28 11:19:16 (GMT +1300)
  v2/ansible/modules/core: (detached HEAD 34784b7a61) last updated 2015/03/15 13:59:05 (GMT +1300)
  v2/ansible/modules/extras: (detached HEAD 400166a655) last updated 2015/03/28 11:19:12 (GMT +1300)
  configured module search path = None
```

The error is:

```
failed: [coconut] => {"changes": ["{\"status\":\"Pulling repository registry.foo.com/ubuntu\"}\r\n", "{\"errorDetail\":{\"message\":\"Authentication is required.\"},\"error\":\"Authentication is required.\"}\r\n"], "failed": true, "status": ""}
msg: Unrecognized status from pull.
```

And yes I'm using nginx in front of the registry with HTTP basic auth.
So it seems username password are not handled (as intended?) to auth against the registry.

The strange thing is, that it even does not work when I successfully login to the registry before and then try to start the image. It still says `Authentication is required`

I tried to remove `username`, `password` and `email`. Same error. And then tried to also remove `registry` from the command. Still the same error. Running it via SSH works perfectly.

**Comment by abadger** [comment]
Okay, are you able to tell me how your setup or playbook differs from what I have in the integration tests I wrote?  I was able to get authentication via nginx's basic auth working for the integration tests so at the moment I can't reproduce your error condtion.  Knowing what differs between how you have things setup and what our integration tests are doing will either point to a bug in the ansible docker module, a misconfiguration, or something that the docker-py python library is unable to do that the docker command line client can.

**Comment by AshleyAitken** [comment]
I seem to have this problem as well...
Any resolution?
Specifically, authenticating to private registries.

**Comment by AshleyAitken** [comment]
```
- name: run container
  docker:
    registry: "registry.co"
    username: "name"
    password: "pass"
    email: "user.name@a.com"
    image: "registry.co/hedventures/{{ item }}{{':'}}0.1-SNAPSHOT"
    name: "{{ item }}"
    state: running
  with_items:
    - a3-write-back
```

may not need the {{':'}} but was trying everything.

Similar issues to what soupdiver has been seeing.

Can successfully login to registry and pull from command line on host
Can run a login shell task and still docker tasks fails "authentication required"
Please share a working docker task for a remote private registry (not Docker Hub)

**Comment by soupdiver** [comment]
I also checked my setup again but can't find any major difference in the playbook or the nginx configuration.
The only difference I can detect somehow is that you run everything on the same machine and I do on different machines.

I also updated `docker-py` to the latest version and the error changed to: `{"error": "DockerException(\"HTTPS endpoint unresponsive and insecure mode isn't enabled.\",)", "failed": true}`

Which I can't really understand. The registry is using a RapidSSL certificate and when I do a curl to the `https://foo.com/v1/_ping` URL it works fine.

When I also use `insecure_registry: yes` it is finally working.

**Comment by SpringStorm5** [comment]
@soupdiver Can you show example with insecure_registry: yes ?

UPD: Thanks! With insecure_registry: yes working

**Comment by ghost** [comment]
`insecure_registry: yes` not working with latest `docker-py` and latest `ansible`
+1

**Comment by jquadrin** [comment]
this works
```yaml
      docker:
        name: es
        email: <email>
        username: <username>
        password: <password>
        image: <image>
        state: running
```

**Comment by crccheck** [comment]
Another possible workaround: I'm doing the pull via `shell` and retagging the image locally so ansible can use its normal logic:

``` yaml
- shell: docker pull docker.example.com/crccheck/helloworld:latest 
- shell: docker tag docker.example.com/crccheck/helloworld:latest helloworld
- docker:
    image: helloworld
    # pull: always
```

Repeated pulls and tags are fast enough where it doesn't matter to me

**Comment by abadger** [comment]
Forgive me, I was on vacation and just now getting back to this.  From the notes about things working with `insecure_registry: yes` it looks like your registry is (perhaps mistakenly) accepting http connections and not https.  So I think ansible's code is fixed at this point but for anyone encountering this problem, there is the need to puzzle out what their registry, docker server, and any proxy in front of the registry is configured to do and then write the ansible playbook to do the same thing.

So I'm going to close this ticket as resolved and people that are still having issues should probably come to the mailing list for help.  If there's further bugs it will probably fall out of being unable to solve things on the mailing list.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by andrenarchy** [comment]
This issue persists in ansible 2. `insecure_registry: yes` is not a solution since I want the connections to be secure. My registry is served via HTTPS-only but the HTTP port is open for redirecting to HTTPS. The host serves multiple domains with SSL via SNI.

Any hints for getting the docker module running without `insecure_registry: yes`?

**Comment by andrenarchy** [comment]
btw: pulling images with the `docker` command works like a charm. So my current workaround is to call `docker pull` before calling the `docker` ansible module:

``` yaml
- name: Pull backend image
  command: "/usr/bin/docker pull docker.paperhive.org/backend:{{backend_tag}}"

- name: Add backend container
  docker:
    name: paperhive-backend
    image: "docker.paperhive.org/backend:{{backend_tag}}"
    state: reloaded
    ports: "127.0.0.1:{{backend_port}}:8000"
    restart_policy: always
    env: "{{backend_env}}"
```

**Comment by ghost** [comment]
If one actually reads documentation, one can find that username and password are for remote docker API and not for authentication to registry. One needs to use docker_login module first. It would be nice if this module allowed specifying registry username and password and worked without leaving this password in ~/.docker/config.json on remote machine.

**Comment by sztupy** [comment]
Also note if you do docker login on OSX or Windows, it will only log you in on your machine, which is not enough, you have to docker login manually on the VM where docker host runs as well
